<a href="https://colab.research.google.com/github/tejaswininridegree/Python-basics-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy- Numeric Python
# Most powerful package - Library

#Numpy- Dimensions
# A-One Dimensionaal Array
# [A,B] || [ A
             #B ]-Two Dimensional Array- Row ||column
# Three Dimensional
# Array-Storing,Manipulating,Similar Data Type
# Faster than any mathematical functions
# Convenient compared to other packages
# Memory Efficiency
# Support Multi Dimensional Arrays
#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)
# memory optimizatin(Numpy)>memory optimization(List operations)

In [ ]:
# Install numpy - pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
# create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
# create 2D array-Matrix
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
# creating Arrays with default values

allZeros = np.zeros((2,3))
print (allZeros)

# creating matrix with all values of elements as '1'

allOnes = np.ones((2,3))
print (allOnes)

#creating matrix with all values of elements 'constant value -n ~ Fill value'


allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
# create an identity matrix -I- Square matrix
identity = np.eye(4)
print(identity)

# Identity matrix-Aii = 1 && Aij = 0
# For all A belongs to R M×N
#Aij-

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Creare a random Matrices

# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

#between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.17931247 0.91781261 0.94048092]
 [0.48912488 0.09751962 0.73252725]
 [0.6519201  0.46285982 0.61092836]]
[[12 12 11]
 [10 13 19]
 [11 17 18]]


In [ ]:
# Array properties
arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)
# shape of the Array
print (f'The shape of the array is {arr.shape}')
# size of the Array
print(f'The size of the array is {arr.size}')
# datatype of the Array
print(f'The Datatype of the array is {arr.dtype}')
# dimensions of array
print(f'The Dimensions of the array is {arr.ndim} ')

[[1 2 3 4]
 [2 3 4 5]]
The shape of the array is (2, 4)
The size of the array is 8
The Datatype of the array is int64
The Dimensions of the array is 2 


In [ ]:
# Indexing and Slicing
# Access the elements in 1D array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])

# Access the elements in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:])# first row with all columns
print(arr2[:,0])# first column with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
# l1 = []
# [l1.append(_) for _ in range(10)]
l1 = np.arange(0,10)
print (l1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
l1 = np.arange(10,0,-1)
print(l1)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# Mathematical Operations
a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'the sum of a and b is {a+b}')
print(f'the diff of a and b is {a-b}')
print(f'the product of a and b is {a*b}')
print(f'the division of a and b is {a/b}')

the sum of a and b is [4 6 8]
the diff of a and b is [-2 -2 -2]
the product of a and b is [ 3  8 15]
the division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
# Matrix Multiplication
b1 = np.array([[1,2,3],[3,4,5]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product --- product =AB -- m×n --B n×p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [48 65]]


In [ ]:
b1

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
b2

array([[5, 6],
       [7, 8],
       [1, 3]])

In [ ]:
print(b1)

[[1 2 3]
 [3 4 5]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
